# Generated by Django 3.1.6 on 2021-02-18 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('third_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='performance',
            field=models.IntegerField(choices=[(1, 'Worst'), (2, 'Bad'), (3, 'Normal'), (4, 'Good'), (5, 'Excelent')]),
        ),
    ]
